# Generated by Django 6.0 on 2026-05-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapersource',
            name='get_item_code',
            field=models.TextField(help_text='Return a DataPayload instance. Use fetch, payload constructors, and preamble helpers.'),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='list_items_code',
            field=models.TextField(help_text='Return List[str] of item URLs. Use fetch, OFFER_URL_PREFIX, and preamble helpers.'),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='list_pages_code',
            field=models.TextField(help_text='Return List[str] of page URLs. Use fetch to retrieve the page and preamble helpers to parse it.'),
        ),
        migrations.AlterField(
            model_name='scrapersource',
            name='preamble_code',
            field=models.TextField(blank=True, help_text='Shared code run before each snippet. Define site-specific helpers here, e.g.:\n  import re, json, html as html_module\n  async def get_next_data(url):\n      resp = await fetch(url, headers={...})\n      ...'),
        ),
    ]
