# Generated by Django 6.0 on 2025-12-17 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdvertiserName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("clean_name", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "db_table": "advertiser_name",
            },
        ),
        migrations.CreateModel(
            name="AdvertiserType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("pl", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "db_table": "advertiser_type",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApartmentListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("city", models.CharField(max_length=128)),
                ("district", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "subdistrict",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "municipality",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("county", models.CharField(blank=True, max_length=128, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("province", models.CharField(blank=True, max_length=128, null=True)),
                ("street", models.CharField(blank=True, max_length=256, null=True)),
                ("latitude", models.DecimalField(decimal_places=12, max_digits=15)),
                ("longitude", models.DecimalField(decimal_places=12, max_digits=15)),
                ("url", models.URLField(unique=True)),
                ("type", models.CharField(max_length=128)),
                (
                    "area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "price_per_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("rooms_num", models.CharField(blank=True, max_length=128, null=True)),
                ("floor_no", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "building_floors_num",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("build_year", models.IntegerField(blank=True, null=True)),
                (
                    "construction_status",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "building_type",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "building_material",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "heating_type",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "ownership_type",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "rent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("advertiser_type", models.CharField(max_length=128)),
                (
                    "advertiser_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "development_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("market_type", models.CharField(max_length=128)),
                ("transaction_type", models.CharField(max_length=128)),
                ("last_seen_at", models.DateTimeField()),
            ],
            options={
                "db_table": "apartment_listing",
            },
        ),
        migrations.CreateModel(
            name="BuildingFloor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("pl", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "db_table": "building_floor",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BuildingMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("pl", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "db_table": "building_material",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BuildingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("pl", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "db_table": "building_type",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConstructionStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("pl", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "verbose_name_plural": "construction_statuses",
                "db_table": "construction_status",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DevelopmentName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("clean_name", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "db_table": "development_name",
            },
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("pl", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "db_table": "floor",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HeatingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("pl", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "db_table": "heating_type",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MarketType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("pl", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "db_table": "market_type",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OwnershipType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("pl", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "db_table": "ownership_type",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PropertyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("pl", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "db_table": "property_type",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("pl", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "db_table": "room",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("pl", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "db_table": "transaction_type",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApartmentListingChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("field_name", models.CharField(max_length=128)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="property.apartmentlisting",
                    ),
                ),
            ],
            options={
                "db_table": "apartment_listing_change",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("city", models.CharField(max_length=128)),
                ("district", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "subdistrict",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "municipality",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("county", models.CharField(blank=True, max_length=128, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("province", models.CharField(blank=True, max_length=128, null=True)),
                ("street", models.CharField(blank=True, max_length=256, null=True)),
                ("latitude", models.DecimalField(decimal_places=12, max_digits=15)),
                ("longitude", models.DecimalField(decimal_places=12, max_digits=15)),
            ],
            options={
                "db_table": "location",
                "unique_together": {
                    (
                        "city",
                        "district",
                        "subdistrict",
                        "municipality",
                        "county",
                        "postal_code",
                        "province",
                        "street",
                        "latitude",
                        "longitude",
                    )
                },
            },
        ),
    ]
