# Generated by Django 6.0 on 2025-12-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("latitude", "longitude")},
        ),
    ]
