# Generated by Django 6.0 on 2025-12-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0002_alter_location_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("pl", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "db_table": "investment_state",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="apartmentlisting",
            name="investment_estimated_delivery",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="apartmentlisting",
            name="investment_state",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
