# Generated by Django 6.0 on 2025-12-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_investmentstate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartmentlisting",
            name="free_from",
            field=models.DateField(blank=True, null=True),
        ),
    ]
