# Generated by Django 6.0 on 2025-12-10 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Domain name (e.g., otodom.pl, facebook.com)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this domain is actively being scraped",
                    ),
                ),
                (
                    "requests_per_second",
                    models.FloatField(
                        default=1.0,
                        help_text="Maximum requests per second (e.g., 0.5 = 1 request every 2 seconds)",
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "delay_between_requests",
                    models.FloatField(
                        default=1.0,
                        help_text="Delay in seconds between requests",
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "concurrent_requests",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of concurrent requests allowed",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Maximum number of retries for failed requests",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "retry_delay",
                    models.FloatField(
                        default=5.0,
                        help_text="Delay in seconds before retrying",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "timeout",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Request timeout in seconds",
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "requests_per_hour",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum requests per hour (None = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or comments"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Domains",
                "ordering": ["name"],
            },
        ),
    ]
