# Generated by Django 6.0 on 2025-12-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='domain',
            table='domain',
        ),
    ]
