# Generated by manual update on 2025-12-11

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0002_alter_domain_table"),
    ]

    operations = [
        # Remove old fields
        migrations.RemoveField(
            model_name="domain",
            name="delay_between_requests",
        ),
        migrations.RemoveField(
            model_name="domain",
            name="requests_per_hour",
        ),
        # Add new fields
        migrations.AddField(
            model_name="domain",
            name="burst_capacity",
            field=models.PositiveIntegerField(
                default=2,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                help_text="Maximum tokens in bucket (allows bursts). Default: 2x requests_per_second",
            ),
        ),
        # Update help text for requests_per_second
        migrations.AlterField(
            model_name="domain",
            name="requests_per_second",
            field=models.FloatField(
                default=1.0,
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(100),
                ],
                help_text="Token refill rate: tokens added per second (e.g., 0.5 = 1 request every 2 seconds)",
            ),
        ),
    ]
