# Generated by Django 6.0 on 2025-12-11 14:53

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("domain", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            (
                                "otodom/sale/apartment/owner",
                                "Otodom - Sale - Apartment - Owner",
                            )
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("list_pages", "List Pages"),
                            ("list_items", "List Items"),
                            ("get_item", "Get Item"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this job is active"
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="domain.domain",
                    ),
                ),
            ],
            options={
                "db_table": "job",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobRunLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule_run_id",
                    core.models.RunIdField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the schedule run",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about execution",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            (
                                "otodom/sale/apartment/owner",
                                "Otodom - Sale - Apartment - Owner",
                            )
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("list_pages", "List Pages"),
                            ("list_items", "List Items"),
                            ("get_item", "Get Item"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "domain_name",
                    core.models.DomainNameField(
                        help_text="Domain name (e.g., otodom.pl, facebook.com)",
                        max_length=255,
                    ),
                ),
                (
                    "parent_job_run_id",
                    core.models.OptionalRunIdField(
                        blank=True,
                        db_index=True,
                        help_text="UUID of the parent job run (if this is a follow-up job)",
                        null=True,
                    ),
                ),
                (
                    "job_run_id",
                    core.models.RunIdField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this job run",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="domain.domain"
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Run Log",
                "verbose_name_plural": "Job Run Logs",
                "db_table": "jobrunlog",
                "ordering": ["-created_at"],
            },
        ),
    ]
