# Generated by Django 6.0 on 2025-12-10 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('otodom/sale/apartment/owner', 'Otodom - Sale - Apartment - Owner')], max_length=255)),
                ('stage', models.CharField(choices=[('list_pages', 'List Pages'), ('list_items', 'List Items'), ('get_item', 'Get Item')], max_length=20)),
                ('url', models.URLField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='domain.domain')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
