# Generated by Django 6.0 on 2025-12-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrunlog',
            name='domain',
        ),
    ]
