# Generated by Django 6.0 on 2025-12-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_remove_jobrunlog_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="source",
            field=models.CharField(
                choices=[
                    (
                        "otodom/sell/apartment/owner",
                        "Otodom - Sell - Apartment - Owner",
                    ),
                    (
                        "otodom/sell/apartment/agency",
                        "Otodom - Sell - Apartment - Agency",
                    ),
                    (
                        "otodom/sell/apartment/developer",
                        "Otodom - Sell - Apartment - Developer",
                    ),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="jobrunlog",
            name="source",
            field=models.CharField(
                choices=[
                    (
                        "otodom/sell/apartment/owner",
                        "Otodom - Sell - Apartment - Owner",
                    ),
                    (
                        "otodom/sell/apartment/agency",
                        "Otodom - Sell - Apartment - Agency",
                    ),
                    (
                        "otodom/sell/apartment/developer",
                        "Otodom - Sell - Apartment - Developer",
                    ),
                ],
                max_length=255,
            ),
        ),
    ]
