# Generated by Django 6.0 on 2025-12-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_is_active_joblog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='job',
            table='job',
        ),
        migrations.AlterModelTable(
            name='joblog',
            table='joblog',
        ),
    ]
