# Generated by Django 6.0 on 2025-12-10 14:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_alter_job_table_alter_joblog_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblog",
            name="run_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for this job run",
            ),
        ),
        migrations.AddField(
            model_name="joblog",
            name="schedule_run_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="UUID of the schedule run that triggered this job (matches ScheduleLog.run_id)",
                null=True,
            ),
        ),
    ]
