# Generated by Django 6.0 on 2026-05-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_remove_source_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrunlog',
            name='source',
            field=models.CharField(help_text="Must match a ScraperSource name, e.g. 'otodom/sell/apartment/owner'", max_length=255),
        ),
    ]
