# Generated by Django 6.0 on 2025-12-11 14:53

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Schedule name", max_length=255, unique=True
                    ),
                ),
                (
                    "cron",
                    models.CharField(
                        help_text="Cron expression (e.g., '0 */6 * * *' for every 6 hours)",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this schedule is active"
                    ),
                ),
                (
                    "next_run",
                    models.DateTimeField(
                        blank=True,
                        help_text="Next scheduled run time (calculated from cron)",
                        null=True,
                    ),
                ),
                (
                    "jobs",
                    models.ManyToManyField(
                        help_text="Jobs to run on this schedule",
                        related_name="schedules",
                        to="job.job",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Schedules",
                "db_table": "schedule",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleRunLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule_run_id",
                    core.models.RunIdField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the schedule run",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about execution",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="schedule.schedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Run Log",
                "verbose_name_plural": "Schedule Run Logs",
                "db_table": "schedulerunlog",
                "ordering": ["-created_at"],
            },
        ),
    ]
