# Generated by Django 6.0 on 2025-12-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_schedulelog"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="schedule",
            table="schedule",
        ),
        migrations.AlterModelTable(
            name="schedulelog",
            table="schedulelog",
        ),
    ]
